aligndir: alignments
outdir: results
logdir: logs
scriptdir: workflow/scripts

samples:
    sample1: 1178
    sample2: 1463
    sample3: 2020
    sample4: 2159

strand:
   R1: R1
   R2: R2

genome: resources/GRCh38_full_analysis_set_plus_decoy_hla.fa #Add genome.fa in resources dir

gentrome: resources/gentrome.fa.gz

gtf: resources/Homo_sapiens.GRCh38.111.gtf

################################
# STAR genome index parameters #
################################
sjdbOverhang: #74 #Put max read length -1

################################
# Hisat2 parameter #
################################
rna_strandness: RF #FR or RF

####################
# HTSeq paramaters #
####################
stranded: reverse
htseqmode: intersection-nonempty
HTSeq_extra: 30

############################
# featureCounts parameters #
############################
strandedfeatureCounts: 1                                                # Modify after check of RNASeq strandness
featureCounts_extra: ' -p --countReadPairs'                             # add if paired_end
#featureCounts_extra: ' -O --fracOverlap 0.2 -p --countReadPairs'       # add if paired_end and count reads of overlapping genes

############################
# salmon parameters #
############################
libType: ISR #ISF or IU

#awk 'NR%4 == 2 {lengths[length($0)]++} END {for (l in lengths) {print l, lengths[l]}}' 1178.R1.sub.fastq

#DESeq from HTSeq count parameters

DESeqFromHTSeqCount:
   count: 10
   alpha: 0.05
   height: 15
   width: 15

DESeqFromFeatureCounts:
   count: 10
   alpha: 0.05
   height: 10
   width: 10
