datadir: 
pipedir: 
aligndir: alignments
outdir: results
logdir: logs
scriptdir: workflow/scripts

samples:
    sample1: A1_CTR
    sample2: A2_CTR
    sample3: A3_TUMOR
    sample4: A4_TUMOR
strand:
   R1: R1
   R2: R2

genome: resources/GRCh38_full_analysis_set_plus_decoy_hla.fa #Add genome.fa in resources dir

gentrome: resources/gentrome.fa.gz

gtf: resources/Homo_sapiens.GRCh38.111.gtf

protein_domain: resources/arriba_v2.4.0/database/protein_domains_hg38_GRCh38_v2.4.0.gff3

blacklist_arriba: resources/arriba_v2.4.0/database/blacklist_hg38_GRCh38_v2.4.0.tsv.gz

known_fusion: resources/arriba_v2.4.0/database/known_fusions_hg38_GRCh38_v2.4.0.tsv.gz

################################
# STAR genome index parameters #
################################
sjdbOverhang: #Put max read length -1

################################
# Hisat2 parameter #
################################
rna_strandness: #None per unstranded

####################
# HTSeq paramaters #
####################
stranded: #reverse per first strand
htseqmode: intersection-nonempty
HTSeq_extra: 30

####################
# arriba paramaters #
####################
strandedAribba: #"no"

############################
# featureCounts parameters #
############################
strandedfeatureCounts: #0 #2 per first strand                            # Modify after check of RNASeq strandness
featureCounts_extra: ' -p --countReadPairs'                             # add if paired_end
#featureCounts_extra: ' -O --fracOverlap 0.2 -p --countReadPairs'       # add if paired_end and count reads of overlapping genes

############################
# salmon parameters #
############################
libType: IU #ISF or IU

#awk 'NR%4 == 2 {lengths[length($0)]++} END {for (l in lengths) {print l, lengths[l]}}' 1178.R1.sub.fastq

############################
# DESeq2 parameters parameters #
############################

DESeqFromHTSeqCount:
   count: 10
   alpha: 0.05
   height: 12
   width: 15

DESeqFromFeatureCounts:
   count: 10
   alpha: 0.05
   height: 12
   width: 15

DESeqFromSalmon:
   count: 10
   alpha: 0.05
   height: 12
   width: 15
